#!/usr/bin/perl

if ($ENV{'REQUEST_METHOD'} eq "POST")
{
   read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
}else {
   $buffer = $ENV{'QUERY_STRING'};
}

@pairs = split(/&/, $buffer);
@name = ();
@value = ();
foreach $pair (@pairs)
{
   ($name, $value) = split(/=/, $pair);
   push(@name, $name);
   push(@value, $value);
}

$flag = 0;
$count = 0;
foreach $i (@name)
{
	if ($i eq "group") {
		if (@value[$count] eq "none") {
			$flag = 1;
		}
	}
	$count++;
}

if ($flag == 1) {
	print "Status: 200 OK", "\n";
	print "Content-type: text/html\n\n";
	print "<html><head>";
	print "<h1>group is not valid</h1>";
	print "</head><body>";
	exit 42;
}

print "Status: 200 OK", "\n";
print "Content-type: text/html\n\n";
print "<html><head></head><body>\n";
$count = 0;
foreach $i (@name)
{
	print "@name[$count]: @value[$count]\n";
	$count++;
}
print "</body></html>";
